openapi: 3.0.3
info:
  version: 1.0.0
  title: Pets API
  description: Pets api 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/ict_statss:
    x-router-controller: petsController
    get:
      description: Returns all ict_statss
      operationId: getIct_statss
      responses:
        200:
          description: Team list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ict_stats'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    
  /api/v1/ict_statss/{year}:
    x-router-controller: petsController
    get:
      description: Returns a single team by its year
      operationId: findByid
      parameters:
        - required: true
          name: year
          description: year of the team to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: Team found by year
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ict_stats'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ict_stats:
        type: object
        required:
          - year
        properties:
          territory:
            type: string
          year:
            type: number
          ict_manufacturing_industry:
            type: number
          wholesale_trade:
            type: number
          edition_of_computer_program:
            type: number
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true